import = [
    "~/.config/alacritty/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14

[env]
TERM  = "xterm-256color"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    {key = "V", mods = "Control", action = "Paste"},
    {key = "=", mods = "Control", action = "IncreaseFontSize"},
    {key = "-", mods = "Control", action = "DecreaseFontSize"},
    {key = "0", mods = "Control", action = "ResetFontSize"}
] 

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
