[general]
import = [
    "~/.config/alacritty/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    {key = "V", mods = "Control", action = "Paste"},
    {key = "=", mods = "Control", action = "IncreaseFontSize"},
    {key = "-", mods = "Control", action = "DecreaseFontSize"},
    {key = "0", mods = "Control", action = "ResetFontSize"},
    {key = "Back", mods = "Control", chars = "\u0017"},
    {key = "Enter", mods = "Command", action = "ToggleFullscreen"},

    {key = "j", mods = "Command", chars = "\u001Bj"},
    {key = "k", mods = "Command", chars = "\u001Bk"},

    {key = ",", mods = "Command", chars = "\u001B,"},
    {key = ".", mods = "Command", chars = "\u001B."},
    {key = "t", mods = "Command", chars = "\u001Bt"},
    {key = "s", mods = "Command", chars = "\u001Bs"}, 
]

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
